openapi: 3.0.0
info:
  title: huc-lambda-API
  description: API used for PO.DAAC feature translation service
  version: 0.1.0
paths:
  /huc/{huc}:
    get:
      operationId: gethuc
      parameters:
        - description: The ID of the HUC to return.
          in: path
          name: huc
          required: true
          schema:
            example: "1701020108"
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '413':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/413'
      summary: Returns associated name and simplified polygon
  /region/{region}:
    get:
      operationId: getregion
      parameters:
        - description: The ID of the region to return.
          in: path
          name: region
          required: true
          schema:
            example: "California Region"
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '413':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/413'
      summary: Returns associated HUC and simplified polygon.
components:
  schemas:
    200:
      description: 200 response from API
      properties:
        bounding_box:
          description: Bounding box for queried region.
          example: "-121.63767546330098,37.04979849040802,-121.48073155937789,37.23308885991514"
          type: string
        full_poly:
          description: Full USGS polygon location.
          example: {
                    s3: "podaac-dev-feature-translation-service",
                    key: "180500030105",
                    shpindex: "12345"
                   }
          type: object
        huc:
          description: HUC identifier for queried region.
          example: "180500030105"
          type: string
        polygon:
          description: Simplified polygon for queried region.
          example: "-121.68307875802219,37.336883989962416,
                    -121.7034261236156,37.335436064964654,
                    -121.72219968921144,37.35039130244144,
                    -121.68307875802219,37.336883989962416"
          type: string
        region:
          description: Region name for queried region.
          example: "California Region"
          type: string
      required:
        - bounding_box
        - full_poly
        - huc
        - polygon
        - region
      type: object
    400:
      description: 400 response from API
      properties:
        error:
          description: "The specified URL is invalid (does not exist)."
          type: string
      required:
        - error
      type: object
    404:
      description: 404 response from API
      properties:
        error:
          description: "An entry with the specified region was not found."
          type: string
      required:
        - error
      type: object
    413:
      description: 413 response from API
      properties:
        error:
          description: "413: Your query has returned is too large."
          type: string
      required:
        - error
      type: object
